export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_00" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_01" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_02" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_03" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_04" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_05" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_06" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_07" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_08" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_09" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_10" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_11" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_12" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_13" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_14" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_15" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --use_mask_query --fps=1 --grid_size=60

# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_00" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_01" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_02" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_03" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_04" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_05" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_06" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_07" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_08" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_09" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_10" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_11" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_12" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_13" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_14" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60
# CUDA_VISIBLE_DEVICES=3 python demo_spatrackerv2.py --data_type="infer" --mask_dir="/mnt/nvme1/semyu/data/dynamic/Technicolor/Undistorted/Birthday" --data_dir="/mnt/nvme1/semyu/data/dynamic/unsync/exp1/Technicolor/Undistorted/Birthday" --video_name="cam_15" --global_pose_from="colmap" --start_timestamp=151 --end_timestamp=201 --query_interval=40 --fps=2 --grid_size=60